### PR TITLE
Pull from Mendicm's fork

### PR DESCRIPTION
**Pull request by petecoop**

### CODE REVIEW

**Comment by petecoop** [comment]
Not sure on benefits for css-to-inline-styles over emogrifier...

**Comment by jasperjorna** [comment]
I noticed that Emogrifier removes the doctype from the template and replaces it with a modern doctype. This seems to break layouts in e-mail clients as they expect an older doctype: `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`.

When I replaced Emogrifier with CssToInlineStyles the problem dissappeared.

Also, CssToInlineStyles is included as a dependency in Laravel's mail system, so maybe it's worth switching?

**Comment by petecoop** [comment]
Hey @jasperjorna thanks for reporting this, I'll add a test for that and re-test this library - but I think CssToInlineStyles is probably the way forward

**Comment by petecoop** [comment]
I've switched to CssToInlineStyles but this doesn't keep the supplied doctype, it appears to always use `<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">`

**Comment by petecoop** [comment]
Closing PR as I've implemented outside of it

**Pull request closed without merging**
